import "../styles/globals.css";
import "../styles/utilities.css";
import "../styles/buttons.css"

// import localFont from "next/font/local";
import Footer   from '@/components/layout/footer'
import Navbar from '@/components/layout/navbar';
import Sidebar  from '@/components/layout/siderbar/siderbar';
import PannelContextProvider from '@/context/PannelContext';

import { graphik, bison } from "@/components/fonts/fonts";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${graphik.className}   bg-polar-mist  `}>
      <PannelContextProvider>
         <nav className=" bg-transparent  ">
          <Navbar />
        </nav>
        <Sidebar/>
        {children}
        <Footer/>
         </PannelContextProvider>
      </body>
     
    </html>
  );
}
